fonts = [
    # nametabl encoding issues, usually foreign names
    'Viga',
    'Voltaire',
    'Snippet',
    'Biryani',
    'Duru Sans',
    'Source Serif Pro',
    'Playfair Display',
    'Pinyon Script',
    'Biryani DemiBold',
    'Biryani UltraLight',
    'Bree Serif',
    'Belgrano',
    'Convergence',
    'Carme',
    'Martel Sans',
    'Playfair Display SC',
    'Sanchez',
    'Lekton',
    'Fresca',
    'Lancelot',
    'Vast Shadow',
    'Tauri',
    'Salsa',
    'Inknut Antiqua',
    'Overpass',
    'Biryani Heavy',
    'Andika',
    'Sofia',
    'Poller One',
    'Poly',
    'Overpass Mono',
    # Dodgy user input names
    'Montserrat Alternates',
    'Montserrat Alternates ExLight',
    'Abril Fatface',
]

existing_pr = [
    'Alfa Slab One',
    'Alice',
    'Amatic SC',
    'Amstelvar',
    'Anaheim',
    'Anton',
    'Archivo',
    'Arsenal',
    'Arvo',
    'Asap',
    'Asap Condensed',
    'Bad Script',
    'Bahiana',
    'Bangers',
    'Barrio',
    'Bevan',
    'Cabin',
    'Cabin Condensed',
    'Cabin Sketch',
    'Catamaran',
    'Checkout',
    'Chivo',
    'Comfortaa',
    'Cormorant',
    'Cormorant Garamond',
    'Cormorant Infant',
    'Cormorant SC',
    'Cormorant Unicase',
    'Cormorant Upright',
    'Cuprum',
    'Cutive Mono',
    'Dancing Script',
    'David Libre',
    'Didact Gothic',
    'Dosis',
    'Ek Mukta',
    'Encode Sans',
    'Encode Sans Condensed',
    'Encode Sans Expanded',
    'Encode Sans Semicondensed',
    'Encode Sans Semiexpanded',
    'Exo',
    'Faustina',
    'Fira Code',
    'Fira Mono',
    'Fira Sans',
    'Fira Sans Compressed',
    'Fira Sans Compressedhairline',
    'Fira Sans Condensed',
    'Fira Sans Condensedhairline',
    'Fira Sans Extra Condensed',
    'Fira Sans Hairline',
    'Fira Sans Ultra',
    'Francoisone',
    'Franksource',
    'Gabriela',
    'Gemunu Libre',
    'Homenaje',
    'Inconsolata',
    'Indie Flower',
    'Josefin Sans',
    'Jura',
    'Kurale',
    'Lalezar',
    'Lato',
    'Lato Hairline',
    'Libre Franklin',
    'Lobster',
    'Lora',
    'Manuale',
    'Markazi Text',
    'Marmelad',
    'Maven Pro',
    'Maven Pro VF',
    'Merriweather',
    'Metrophobic',
    'Mina',
    'Montserrat',
    'Montserrat Alternates',
    'Montserrat Alternates ExLight',
    'Mukta',
    'Mukta Malar',
    'Mukta Vaani',
    'Muli',
    'Neuton',
    'Nunito',
    'Nunito Heavy',
    'Nunito Sans',
    'Oldstandard TT',
    'Oswald',
    'Oswald Heavy',
    'Overpass',
    'Overpass Mono',
    'Pacifico',
    'Pangolin',
    'Philospher',
    'Play',
    'Podkova',
    'Poiretone',
    'Post No Bills Colombo',
    'Post No Bills Jaffna',
    'Prata',
    'Press Start 2p',
    'Quicksand',
    'Raleway',
    'Roboto',
    'Roboto Condensed',
    'Rokkitt',
    'Ropa Sans',
    'Rubik',
    'Rubik Mono One',
    'Saira',
    'Saira Condensed',
    'Saira Extra Condensed',
    'Saira Semi Condensed',
    'Sansita',
    'Scada',
    'Sharetech',
    'Sigmar One',
    'Source Serif Pro',
    'Telex',
    'Trocchi',
    'Unna',
    'Varela Round',
    'Vfbetas',
    'Vollkorn',
    'VT323',
    'Yaldevi Colombo',
    'Yaldevi Jaffna',
    'Yanone Kaffeesatz',
    'Yeseva One',
]
